[package]
name = "ood-daemon"
version = "0.5.0"
authors = ["liyaxing <liyaxing@buckyos.com>"]
edition = "2018"
license = "BSD-2-Clause"
description = "Rust ood-daemon package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-bdt = { path = "../../component/cyfs-bdt" }
cyfs-util = { path = "../../component/cyfs-util" }
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-core = { path = "../../component/cyfs-core" }
cyfs-debug = { path = "../../component/cyfs-debug" }
cyfs-meta-lib = { path = "../../component/cyfs-meta-lib" }
cyfs-client = { path = "../../tools/cyfs-client" }
base = { path = "../base", default-features = false, features = ["mongo"] }
ood-control = { path = "../ood-control" }
lazy_static = "1.4"
serde = "1.0"
serde_json = "1.0"
log = "0.4"
zip = "0.6"
async-trait = "0.1.53"
futures-util = "0.3"
url = "2.2"
async-std = { version = "1.11", features = ["unstable", "attributes"] }
fs_extra = "1.2"
futures = "0.3"
clap = "2.34.0"
async-h1 = "2.3.3"
once_cell = "1.12"
toml = "0.5"
