[package]
name = "dsg-service"
version = "0.5.0"
edition = "2021"
license = "BSD-2-Clause"
description = "Rust dsg-service package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "=0.4.16"
async-std = { version = "1.8", features = ["std"] }
async-trait = "0.1.53"
async-recursion = "1.0.0"
sha2 = "0.8.2"
rand = "0.8.5"
cyfs-base = {path="../../component/cyfs-base", version = "0.5"}
cyfs-debug = {path="../../component/cyfs-debug", version = "0.5"}
cyfs-util = {path="../../component/cyfs-util", version = "0.5"}
cyfs-bdt = {path="../../component/cyfs-bdt", version = "0.5"}
cyfs-lib = {path="../../component/cyfs-lib", version = "0.5"}
dsg-client = {package="cyfs-dsg-client", path="../../component/cyfs-dsg-client", version = "0.5"}
