[package]
name = "cyfs-container"
version = "0.5.0"
authors = ["liyaxing <liyaxing@buckyos.com>"]
edition = "2021"
license = "BSD-2-Clause"
description = "Rust cyfs-container package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
async-std = { version = "1.11", features = ["attributes"] }
async-trait = "0.1.53"
futures = "0.3"
cyfs-util = { path = "../../component/cyfs-util" }
cyfs-bdt = { path = "../../component/cyfs-bdt" }
cyfs-base = { path = "../../component/cyfs-base" }
cyfs-debug = { path = "../../component/cyfs-debug" }
cyfs-lib = { path = "../../component/cyfs-lib" }
cyfs-stack-loader = { path = "../../component/cyfs-stack-loader" }
# im-service = {path="../../product/cyim/im-service", features = ["http"]}
