[package]
name = "cyfs-meta-miner"
version = "0.5.0"
authors = ["tsukasa <sichangjun@buckyos.com>"]
edition = "2018"
license = "BSD-2-Clause"
description = "Rust cyfs-meta-miner package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cyfs-base={ path = "../../component/cyfs-base"}
cyfs-meta= {path="../cyfs-meta"}
cyfs-debug={ path = "../../component/cyfs-debug"}
tide = "0.16"
hex = "0.4"
async-std = { version = "1.11", features = ["attributes"] }
lazy_static = "1.4"
log = "0.4"
clap = "2.34.0"
