[package]
name = "cyfs-meta-genesis"
version = "0.5.0"
authors = ["swjtusw <swjtusw@126.com>"]
edition = "2018"
license = "BSD-2-Clause"
description = "Rust cyfs-meta-genesis package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyfs-meta={path="../cyfs-meta"}
commandlines = "0.8.0"
serde_json = "1.0"
simple_logger = "2.1"
log = "0.4"
