matrix:
  fast_finish: true
  include:
    - name: Run tests
      language: rust
      rust: stable
      install:
        []
      before_script:
        - cargo install cargo-deny --version 0.6.8
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - make test

    - name: Run CPython wrapper tests
      language: rust
      rust: stable
      install:
        []
      before_script:
        - cargo install cargo-deny
        - rustup component add rustfmt
        - rustup component add clippy
        - sudo apt update && sudo apt install python3 python3-pip python3-dev python3-venv
        - pip3 install --upgrade pip
        - pip3 install maturin
        - python3 -m venv venv
      script:
        - source venv/bin/activate && make test_py
