[package]
name = "cyfs-meta-client"
version = "0.5.0"
authors = ["liuzhicong <liuzhicong@buckyos.com>"]
edition = "2018"
license = "BSD-2-Clause"
description = "Rust cyfs-meta-client package"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.11"
http-types = "2.12"
async-h1 = "2.3.3"
hex = "0.4"
cyfs-base={path="../../component/cyfs-base"}
cyfs-base-meta={path="../../component/cyfs-base-meta"}
cyfs-meta-lib = {path="../../component/cyfs-meta-lib"}
cyfs-util = {path="../../component/cyfs-util"}
log = "0.4"
clap = "2.34.0"
dirs = "4.0"
simple_logger = "2.1"
async-recursion = "1.0"
lazy_static = "1.4"
serde_json = "1.0"
rand = "0.7.3"
ethabi = {path="../../3rd/ethabi"}
